AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-tpb-crawl

  Sample SAM Template for sam-tpb-crawl

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 25

Resources:
  TpbCrawlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - S3CrudPolicy: { "BucketName": "tpb-snapshots-html" }
        - SSMParameterReadPolicy: { "ParameterName": "SCRAPER_API_KEY" }
      PackageType: Image
      MemorySize: 2048
      Architectures:
        - x86_64
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 */4 * * ? *)
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./sam-tpb-crawl
      Dockerfile: Dockerfile

Outputs:
  TpbCrawlFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TpbCrawlFunction.Arn
  TpbCrawlFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TpbCrawlFunctionRole.Arn
